### PR TITLE
Fix crash when reading HiDGuardian registry

### PR DESCRIPTION
**Pull request by jmriego**
This pull request solves the issue #183 .
I am not capturing the serial number as it seems like it's not necessary, but if it was, this code could do that:
`split_regex = re.compile("HID\\\\VID_([a-zA-Z0-9]+)&PID_([a-zA-Z0-9]+)(?:&REV_([a-zA-Z0-9]+))?")`

Honored to do the first pull request! I really like your app after trying every other similar one like UCR, Freepie, Glovepie... and I have several years of experience with Python. So I would be happy to help with some other issues if you want

### CODE REVIEW

**Comment by WhiteMagic** [comment]
Thanks for the fix, though I think this would not solve the issue entirely, as the regex is used with match method which requires to find the complete expression as opposed to just a part of it. From looking at the cases where the code failed it is caused by an additional term existing on top of the VID and PID the current code is looking for.

Capturing the REV value probably is also not going to work as I have one example that contains another third term (https://dto9r5vaiz7bu.cloudfront.net/v012w5fh7xvnw/tavern_upload_large.png) so it seems that VID and PID are guaranteed to exist with additional random stuff.

I think the safest solution is to have regex similar to this:
```re.compile("^HID\\\\VID_([a-fA-F0-9]{4})&PID_([a-fA-F0-9]{4}).*$")```
This should capture 2 groups of 4 hex values with the potential of additional stuff at the end. 

As these two matches are then later on interpreted as hex values and the failing of that cast causes the problem it probably can't hurt to put that part into a try catch and log + display in case of a failure and then continue so Gremlin doesn't crash but the user is informed of the issue.

**Comment by jmriego** [comment]
Happy to help! I think both ways should work. The match method returns a match if the regex is found at the start of the string. Trying both options, they seem to give the same result here:

```
def test_regex(entry, split_regex):
    split_regex = re.compile(split_regex)
    match = split_regex.match(entry)
    return [match_group(match, i) for i in range(4)]

print test_regex('HID\VID_046D&PID_C216&REV_0300', "HID\\\\VID_([a-zA-Z0-9]+)&PID_([a-zA-Z0-9]+)")
print test_regex('HID\VID_046D&PID_C216', "HID\\\\VID_([a-zA-Z0-9]+)&PID_([a-zA-Z0-9]+)")
print test_regex('HID\VID_046D&PID_C216', "^HID\\\\VID_([a-fA-F0-9]{4})&PID_([a-fA-F0-9]{4}).*$")
print test_regex('HID\VID_046D&PID_C216', "^HID\\\\VID_([a-fA-F0-9]{4})&PID_([a-fA-F0-9]{4}).*$")
```

Anyway, I'll have a look at the logging functions JoystickGremlin is using and modify the code. Thanks for checking this!

**Comment by jmriego** [comment]
I have modified the code to add an error message when not being able to load from the HidGuardian registry. I have modified the regex to get the four characters next to PID and VID even if they are not an hexadecimal number. That way, if there's a problem, it will show a dialog instead of not hitting the re.match part and masking that there is a registry entry it cannot read.
I can change it back if necessary. By the way, I'd rebase all the commits together before the merge to keep a cleaner history

**Comment by WhiteMagic** [comment]
Thanks for this I'll have a look over it tomorrow but from the quick glance it looks like this should work fine.

**Comment by WhiteMagic** [comment]
Thanks for your work on fixing this. At the moment I'm doing some kind of open heart surgery with replacing SDL2 so there might be quite a bit of underlying change. Things that tend to be somewhat independent are containers and actions.

**Comment by jmriego** [comment]
No worries! Always good to give back a bit of help after using such a nice program. Good luck! I wouldn't even know where to start looking into SDL2 or alternatives 😆 
I'll have a look at the open issues and see what can I do related to containers and actions. Cheers

**Pull request merged**
